import Link from 'next/link'
import './globals.css'


//제목을 바꾸고 싶을 때는 metadata 가져오기
export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by yh',
}

export default async function RootLayout({ children }) {


  const res = await fetch('http://localhost:9999/topics')
  const topics = await res.json();
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topic)=>
            <li key ={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          
          )}
        </ol>
        {children}
        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update/1'>Update</Link></li>
          <li><input type="button" value="delete" /></li>
          
        </ul>
        </body>
    </html>
  )
}
